### ISSUE TITLE
Live Demo Link is Broken

### ISSUE THREAD

**Issue by dudis** [railsadminteam/rails_admin#3638] opened 2023-07-12 10:35 UTC
The "**Try the [live demo]**" Link (http://rails-admin-tb.herokuapp.com/) on README (Getting started session) is broken.

It's showing a Heroku default application error page.

**Comment by codealchemy** [comment] 2023-07-12 15:10
Dupe of https://github.com/railsadminteam/rails_admin/issues/3537

**Closed by codealchemy** 2023-07-12 15:10 UTC
