### ISSUE TITLE
Need install instructions for webpacker => shakapacker v6

### ISSUE THREAD

**Issue by justin808** [railsadminteam/rails_admin#3576] opened 2022-11-30 19:34 UTC
**Describe the bug**

Upgrades to Rails 7 and Rails admin 3.1 touches the webpacker setup

One possible error:

```
ParserError: Syntax Error at line: 1, column 30
```

I'll see what I can do to help out with this. 

Please add comments here, and feel free to comment here: https://github.com/shakacode/shakapacker/issues.

**Comment by mshibuya** [comment] 2022-12-04 09:43
The issue itself is duplicate of #3565. Currently there's nothing preventing using RailsAdmin with Shakapacker.

**Closed by mshibuya** 2022-12-04 09:43 UTC
