### ISSUE TITLE
ActionView::Template::Error: undefined method `status_cache' for #<Xxx

### ISSUE THREAD

**Issue by seb-sykio** [railsadminteam/rails_admin#3456] opened 2022-01-05 14:08 UTC
File  shared/bundle/ruby/3.0.0/gems/activemodel-7.0.0/lib/active_model/attribute_methods.rb line 458 in method_missing
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/fields/types/file_upload.rb line 27 in public_send
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/fields/types/file_upload.rb line 27 in block in <class:FileUpload>
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/configurable.rb line 75 in instance_eval
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/configurable.rb line 75 in block in register_instance_option
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/views/rails_admin/main/_form_file_upload.html.erb line 3 in __ _app_views_rails_admin_main__form_file_upload_html_erb__1556826209688355776_430500
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/base.rb line 244 in public_send
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/base.rb line 244 in _run
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/template.rb line 157 in block in render
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 208 in instrument
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/template.rb line 361 in instrument_render_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/template.rb line 155 in render
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/partial_renderer.rb line 251 in block in render_partial_template
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in block in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications/instrumenter.rb line 24 in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in instrument
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/partial_renderer.rb line 246 in render_partial_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/partial_renderer.rb line 237 in render
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/renderer.rb line 81 in render_partial_to_object
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/renderer.rb line 27 in render_to_object
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/renderer.rb line 22 in render
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/rendering_helper.rb line 38 in block in render
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/base.rb line 270 in in_rendering_context
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/rendering_helper.rb line 34 in render
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/fields/base.rb line 251 in block in <class:Base>
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/configurable.rb line 75 in instance_eval
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/configurable.rb line 75 in block in register_instance_option
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/proxyable/proxy.rb line 25 in method_missing
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 75 in field_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 60 in block in input_for
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in block in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 209 in with_output_buffer
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/tag_helper.rb line 338 in content_tag
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 59 in input_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 49 in block in field_wrapper_for
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in block in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 209 in with_output_buffer
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/tag_helper.rb line 338 in content_tag
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 46 in field_wrapper_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 37 in block (2 levels) in fieldset_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 37 in collect
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 37 in block in fieldset_for
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in block in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 209 in with_output_buffer
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/tag_helper.rb line 338 in content_tag
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 33 in fieldset_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 18 in block (2 levels) in generate
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 17 in collect
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 17 in block in generate
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 133 in without_field_error_proc_added_div
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/form_builder.rb line 9 in generate
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/views/rails_admin/main/edit.html.erb line 2 in block in __ _app_views_rails_admin_main_edit_html_erb__2216751547365151193_426700
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in block in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 209 in with_output_buffer
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/capture_helper.rb line 45 in capture
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/form_helper.rb line 768 in form_with
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/helpers/form_helper.rb line 460 in form_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/helpers/rails_admin/main_helper.rb line 7 in rails_admin_form_for
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/views/rails_admin/main/edit.html.erb line 1 in __ _app_views_rails_admin_main_edit_html_erb__2216751547365151193_426700
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/base.rb line 244 in public_send
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/base.rb line 244 in _run
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/template.rb line 157 in block in render
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 208 in instrument
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/template.rb line 361 in instrument_render_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/template.rb line 155 in render
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/template_renderer.rb line 65 in block (2 levels) in render_template
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in block in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications/instrumenter.rb line 24 in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in instrument
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/template_renderer.rb line 60 in block in render_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/template_renderer.rb line 75 in block in render_with_layout
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in block in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications/instrumenter.rb line 24 in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in instrument
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/template_renderer.rb line 74 in render_with_layout
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/template_renderer.rb line 59 in render_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/template_renderer.rb line 11 in render
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/renderer.rb line 61 in render_template_to_object
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/renderer/renderer.rb line 29 in render_to_object
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/rendering.rb line 117 in block in _render_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/base.rb line 270 in in_rendering_context
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/rendering.rb line 116 in _render_template
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/streaming.rb line 216 in _render_template
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/rendering.rb line 103 in render_to_body
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/rendering.rb line 46 in render_to_body
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/renderers.rb line 142 in render_to_body
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/abstract_controller/rendering.rb line 25 in render
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/rendering.rb line 30 in render
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/instrumentation.rb line 22 in block (2 levels) in render
File /usr/local/lib/ruby/3.0.0/benchmark.rb line 308 in realtime
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/core_ext/benchmark.rb line 14 in ms
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/instrumentation.rb line 22 in block in render
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/instrumentation.rb line 91 in cleanup_view_runtime
File  shared/bundle/ruby/3.0.0/gems/activerecord-7.0.0/lib/active_record/railties/controller_runtime.rb line 34 in cleanup_view_runtime
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/instrumentation.rb line 21 in render
File  shared/bundle/ruby/3.0.0/bundler/gems/wicked_pdf-769f9df487f3/lib/wicked_pdf/pdf_helper.rb line 18 in render
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/actions/edit.rb line 20 in block (4 levels) in <class:Edit>
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/mime_responds.rb line 214 in respond_to
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/lib/rails_admin/config/actions/edit.rb line 19 in block (2 levels) in <class:Edit>
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/controllers/rails_admin/main_controller.rb line 39 in instance_eval
File  shared/bundle/ruby/3.0.0/bundler/gems/rails_admin-da51b91f712b/app/controllers/rails_admin/main_controller.rb line 39 in action_missing
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/abstract_controller/base.rb line 228 in _handle_action_missing
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/basic_implicit_render.rb line 6 in send_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/abstract_controller/base.rb line 214 in process_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/rendering.rb line 53 in process_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/abstract_controller/callbacks.rb line 234 in block in process_action
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb line 118 in block in run_callbacks
File  shared/bundle/ruby/3.0.0/gems/actiontext-7.0.0/lib/action_text/rendering.rb line 20 in with_renderer
File  shared/bundle/ruby/3.0.0/gems/actiontext-7.0.0/lib/action_text/engine.rb line 69 in block (4 levels) in <class:Engine>
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb line 127 in instance_exec
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb line 127 in block in run_callbacks
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb line 138 in run_callbacks
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/abstract_controller/callbacks.rb line 233 in process_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/rescue.rb line 22 in process_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/instrumentation.rb line 67 in block in process_action
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in block in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications/instrumenter.rb line 24 in instrument
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb line 206 in instrument
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/instrumentation.rb line 66 in process_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/params_wrapper.rb line 259 in process_action
File  shared/bundle/ruby/3.0.0/gems/activerecord-7.0.0/lib/active_record/railties/controller_runtime.rb line 27 in process_action
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/abstract_controller/base.rb line 151 in process
File  shared/bundle/ruby/3.0.0/gems/actionview-7.0.0/lib/action_view/rendering.rb line 39 in process
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb line 188 in dispatch
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb line 251 in dispatch
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb line 49 in dispatch
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb line 32 in serve
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb line 50 in block in serve
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb line 32 in each
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb line 32 in serve
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb line 850 in call
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/engine.rb line 530 in call
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/railtie.rb line 224 in public_send
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/railtie.rb line 224 in method_missing
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/mapper.rb line 19 in block in <class:Constraints>
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/mapper.rb line 48 in serve
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb line 50 in block in serve
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb line 32 in each
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb line 32 in serve
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb line 850 in call
File  shared/bundle/ruby/3.0.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb line 202 in call!
File  shared/bundle/ruby/3.0.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb line 169 in call
File  shared/bundle/ruby/3.0.0/gems/rack-pjax-1.1.0/lib/rack/pjax.rb line 12 in call
File  shared/bundle/ruby/3.0.0/gems/rack-attack-6.5.0/lib/rack/attack.rb line 99 in call
File  shared/bundle/ruby/3.0.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb line 14 in call
File  shared/bundle/ruby/3.0.0/gems/rack-attack-6.5.0/lib/rack/attack.rb line 113 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/deflater.rb line 44 in call
File  shared/bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb line 36 in block in call
File  shared/bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb line 34 in catch
File  shared/bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb line 34 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb line 15 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/etag.rb line 27 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/conditional_get.rb line 27 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/head.rb line 12 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/http/permissions_policy.rb line 22 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/http/content_security_policy.rb line 18 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb line 266 in context
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb line 260 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/cookies.rb line 693 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/callbacks.rb line 27 in block in call
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb line 99 in run_callbacks
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/callbacks.rb line 26 in call
File  shared/bundle/ruby/3.0.0/gems/rollbar-3.3.0/lib/rollbar/middleware/rails/rollbar.rb line 25 in block in call
File  shared/bundle/ruby/3.0.0/gems/rollbar-3.3.0/lib/rollbar.rb line 145 in scoped
File  shared/bundle/ruby/3.0.0/gems/rollbar-3.3.0/lib/rollbar/middleware/rails/rollbar.rb line 22 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/debug_exceptions.rb line 28 in call
File  shared/bundle/ruby/3.0.0/gems/rollbar-3.3.0/lib/rollbar/middleware/rails/show_exceptions.rb line 22 in call_with_rollbar
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/show_exceptions.rb line 26 in call
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/rack/logger.rb line 36 in call_app
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/rack/logger.rb line 25 in block in call
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb line 99 in block in tagged
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb line 37 in tagged
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb line 99 in tagged
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/rack/logger.rb line 25 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/remote_ip.rb line 93 in call
File  shared/bundle/ruby/3.0.0/gems/request_store-1.5.0/lib/request_store/middleware.rb line 19 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/request_id.rb line 26 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb line 24 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb line 22 in call
File  shared/bundle/ruby/3.0.0/gems/activesupport-7.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb line 29 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/executor.rb line 14 in call
File  shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb line 110 in call
File  shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/host_authorization.rb line 131 in call
File  shared/bundle/ruby/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb line 100 in call
File  shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/engine.rb line 530 in call
File /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb line 107 in process_request
File /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb line 149 in accept_and_process_next_request
File /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb line 110 in main_loop
File /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb line 416 in block (3 levels) in start_threads
File /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb line 113 in block in create_thread_and_abort_on_exception

**Comment by codealchemy** [comment] 2022-01-05 20:34
Can you please include the configuration for the field in question (and/or use the [bug report template](https://github.com/railsadminteam/rails_admin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md))? This looks to be thrown when rendering the file upload form due to how the field is configured, and `Carrierwave` looks to be the only type that matches the pattern seen here (so it could be an upstream change that broke the integration here, or the field is incorrectly configured)

https://github.com/railsadminteam/rails_admin/blob/da51b91f712b235c0c6e2a120724fcb31ff28168/lib/rails_admin/config/fields/types/file_upload.rb#L26-L28

https://github.com/railsadminteam/rails_admin/blob/da51b91f712b235c0c6e2a120724fcb31ff28168/lib/rails_admin/config/fields/types/file_upload.rb#L22-L24

https://github.com/railsadminteam/rails_admin/blob/da51b91f712b235c0c6e2a120724fcb31ff28168/lib/rails_admin/config/fields/types/carrierwave.rb#L19-L21

**Comment by seb-sykio** [comment] 2022-01-06 08:24
no sure which configuration you meant. If from initializers/rails_admin.rb :

`      field :logo, :carrierwave`

**Comment by TruffeCendree** [comment] 2022-01-06 11:09
Thanks @codealchemy for your help. I just started a Github Sponsoring in return.

I am working with @seb-sykio and I have just found the error. The carrierware uploader in missing in our model because of a recent refactoring.

**Comment by codealchemy** [comment] 2022-01-06 22:14
Got it, thanks @TruffeCendree ! 

Sounds like you've got the cause nailed down, so I'll close this issue out - please let me know if I'm misreading things here and it should stay open. cc: @seb-sykio

**Closed by codealchemy** 2022-01-06 22:14 UTC
