### ISSUE TITLE
V3.0.0.alpha : running in production is breaking

### ISSUE THREAD

**Issue by RocKhalil** [railsadminteam/rails_admin#3420] opened 2021-11-16 14:22 UTC
For some reason, customizing actions ( or even including them ) in `initializers/rails_admin.rb` is breaking;

```rb
def add_action_custom_key(action, &block)
  action.instance_eval(&block) if block
  @@actions ||= []
  if action.custom_key.in?(@@actions.collect(&:custom_key))
    raise "Action #{action.custom_key} already exists. Please change its custom key."
  else
    @@actions << action
  end
end
```

Thrown error:
```
add_action_custom_key: Action dashboard already exists. Please change its custom key. (RuntimeError)
```

**Comment by RocKhalil** [comment] 2021-11-16 14:53
This can fix it, but didn't give it too much time to test:

`lib/rails_admin/config/actions.rb`

```
def default_actions
  @@default_actions ||= [
    Dashboard.new,
    Index.new,
    Show.new,
    New.new,
    Edit.new,
    Export.new,
    Delete.new,
    BulkDelete.new,
    HistoryShow.new,
    HistoryIndex.new,
    ShowInApp.new,
  ]
end

def init_actions!
  @@actions ||= default_actions
end

def add_action_custom_key(action, &block)
  action.instance_eval(&block) if block
  @@actions ||= []
  default_actions_keys = default_actions.collect(&:custom_key)
  exsting_actions_keys = @@actions.collect(&:custom_key)

  # we might be overriding a default action
  if action.custom_key.in?(exsting_actions_keys) && !action.custom_key.in?(default_actions_keys)
    raise "Action #{action.custom_key} already exists. Please change its custom key."
  else
    @@actions << action
  end
end
```

**Comment by mshibuya** [comment] 2021-11-25 07:09
How does you `config/initializers/rails_admin.rb` look like?

**Comment by RocKhalil** [comment] 2021-11-25 07:37
@mshibuya 

```
RailsAdmin.config do |config|
  ### Popular gems integration

  ## == Devise ==
  config.authenticate_with do
    warden.authenticate! scope: :user
  end
  config.current_user_method(&:current_user)

  ## == Cancan ==
  # config.authorize_with :cancan

  config.parent_controller = '::ApplicationController'

  ## == Pundit ==
  # config.authorize_with :pundit

  ## == PaperTrail ==
  # config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0

  ### More at https://github.com/sferik/rails_admin/wiki/Base-configuration

  ## == Gravatar integration ==
  ## To disable Gravatar integration in Navigation Bar set to false
  # config.show_gravatar = true

  config.actions do
    dashboard do
      statistics false # to disable the models load
    end

    index # mandatory

    new do
      except [
        UserAction,
        SystemLog,
        Song, SongAction, SongStat, SongStatsExternal
      ]
    end

    export

    bulk_delete do
      except [
        User,
        UserAction,
        SystemLog,
        SongAction, SongStat, SongStatsExternal
      ]
    end

    show

    edit do
      except [
        UserAction,
        SystemLog,
        SongAction, SongStat, SongStatsExternal
      ]
    end

    delete do
      except [
        User,
        UserAction,
        SystemLog,
        SongAction, SongStat, SongStatsExternal
      ]
    end

    show_in_app
    ## With an audit adapter, you can add:
    # history_index
    # history_show

    I18n.load_path += Dir["#{Rails.root}/lib/rails_admin/locales/*.yml"]
    Dir["#{Rails.root}/lib/rails_admin/actions/*.rb"].map { |f| [f, require(f)] }
    Dir["#{Rails.root}/lib/rails_admin/configuration/*.rb"].map { |f| [f, require(f)] }

    %i[approved live expired not_a_fit].each do |status|
      eval(''"
        song_status_update_#{status} do
          only [Song]
        end
      "'')
    end

    %i[claimed released].each do |status|
      eval(''"
        song_match_status_update_#{status} do
          only [SongMatch]
        end
      "'')
    end
  end
end
```

This works fine with Version 2.X

**Comment by mshibuya** [comment] 2021-11-25 08:53
Hmm I can't reproduce locally...
Could you provide the full stack trace of this error?
```
add_action_custom_key: Action dashboard already exists. Please change its custom key. (RuntimeError)
```

**Comment by RocKhalil** [comment] 2021-11-25 08:57
Did you try to run it with `RAILS_ENV=production` ? it's working on dev environment but not on production

**Comment by RocKhalil** [comment] 2021-11-25 08:58
Basically, the `add_action_custom_key` error shows for `dashboard`, `new`, `index` etc... ( the main actions used by rails admin )

**Comment by mshibuya** [comment] 2021-11-25 09:33
Thanks, I could reproduce. This issue should be related to this change, I'll investigate...

**Comment by mshibuya** [comment] 2021-11-25 10:53
Pushed a fix in a branch, could you try it by putting
```
gem 'rails_admin', github: 'railsadminteam/rails_admin', branch: 'fix-initialization'
```

into your Gemfile?

**Comment by RocKhalil** [comment] 2021-11-25 11:37
Works perfectly !
Thanks for the quick fix

**Closed** 2021-12-18 05:30 UTC
