### ISSUE TITLE
rails_admin can not export to local

### ISSUE THREAD

**Issue by ciscolive** [railsadminteam/rails_admin#3481] opened 2022-02-27 09:11 UTC
returned follow error 
```ruby
application-9b2864b570e0ad6a26e64df4aa210eec14e88c68cdf6ddcebcd1b6680b4fee6b.js:2907 Error: Form responses must redirect to another location
    at FormSubmission.requestSucceededWithResponse (application-9b2864b570e0ad6a26e64df4aa210eec14e88c68cdf6ddcebcd1b6680b4fee6b.js:1438:21)
    at FetchRequest.receive (application-9b2864b570e0ad6a26e64df4aa210eec14e88c68cdf6ddcebcd1b6680b4fee6b.js:1198:21)
    at FetchRequest.perform (application-9b2864b570e0ad6a26e64df4aa210eec14e88c68cdf6ddcebcd1b6680b4fee6b.js:1176:25)
```

please help

**Comment by mshibuya** [comment] 2022-02-27 09:50
Duplicate of https://github.com/railsadminteam/rails_admin/pull/3461#issuecomment-1048588801.

**Closed by mshibuya** 2022-02-27 09:50 UTC
